"""Regenerate the README's API section from BinjaAPI.

    PYTHONPATH=/path/to/binaryninja/python python3 scripts/generate_docs.py

Rewrites everything between the API markers in README.md. The list is rendered from the class by
introspection, the same way the tool description the LLM reads is, so the two cannot disagree.
"""

import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT.parent))

from binja_codemode_mcp.plugin import tools  # noqa: E402
from binja_codemode_mcp.plugin.api import BinjaAPI  # noqa: E402

README = ROOT / "README.md"
BEGIN = "<!-- BEGIN GENERATED API -->"
END = "<!-- END GENERATED API -->"


def render_markdown(surface):
    """Render the API surface as the README's method list."""
    lines = [BEGIN, "", "_Generated by `scripts/generate_docs.py` from `plugin/api.py`._"]
    for section, names in tools.group_by_section(surface).items():
        lines += ["", f"### {section}", ""]
        for name in names:
            method = surface[name]
            signature = tools.method_signature(method)
            lines.append(f"- `binja.{name}{signature}` — {tools.method_summary(method)}")
    return "\n".join(lines + ["", END])


def splice(text, block):
    """Replace the marked region of the README, leaving everything around it alone."""
    if BEGIN not in text or END not in text:
        raise SystemExit(f"README.md is missing the {BEGIN} / {END} markers.")
    head, rest = text.split(BEGIN, 1)
    _, tail = rest.split(END, 1)
    return f"{head}{block}{tail}"


def main():
    block = render_markdown(tools.api_surface(BinjaAPI))
    updated = splice(README.read_text(), block)
    if updated == README.read_text():
        print("README.md already up to date")
        return
    README.write_text(updated)
    print(f"Wrote the API section of README.md ({block.count(chr(10)) + 1} lines)")


if __name__ == "__main__":
    main()
